import type { ComponentType } from "react";

/**
 * Slug -> dynamic-import loader for each tool's actual component.
 * Deliberately kept separate from config/tools.ts (structural metadata:
 * icon, slug, name, priority, relatedSlugs) so client components that only
 * need metadata (BentoToolGrid, RecentToolsShelf, CommandMenu, SiteHeader,
 * ToolGrid, ...) never pull this file's import() graph into their bundle.
 * Previously, all 43 component loaders lived inline in config/tools.ts,
 * which every one of those client components also imported for metadata —
 * that dragged heavy tool bundles (e.g. pdf-lib) into the homepage's initial
 * JS. Only app/[locale]/tools/[category]/[slug]/page.tsx should import this file.
 */
export const TOOL_COMPONENT_LOADERS: Record<string, () => Promise<{ default: ComponentType }>> = {
  "jpg-to-png": () => import("@/components/tools/media/ImageConverter"),
  "merge-pdf": () => import("@/components/tools/document/MergePdf"),
  "json-formatter": () => import("@/components/tools/developer/JsonFormatter"),
  "salary-to-hourly": () => import("@/components/tools/financial/SalaryToHourly"),
  "heic-to-jpg": () => import("@/components/tools/media/HeicToJpg"),
  "image-compressor": () => import("@/components/tools/media/ImageCompressor"),
  "image-resizer": () => import("@/components/tools/media/ImageResizer"),
  "webp-converter": () => import("@/components/tools/media/WebpConverter"),
  "png-to-jpg": () => import("@/components/tools/media/PngToJpg"),
  "base64-image-encoder": () => import("@/components/tools/media/Base64ImageEncoder"),
  "favicon-generator": () => import("@/components/tools/media/FaviconGenerator"),
  "qr-code-generator": () => import("@/components/tools/media/QrCodeGenerator"),
  "color-picker": () => import("@/components/tools/media/ColorPicker"),
  "split-pdf": () => import("@/components/tools/document/SplitPdf"),
  "pdf-to-images": () => import("@/components/tools/document/PdfToImages"),
  "images-to-pdf": () => import("@/components/tools/document/ImagesToPdf"),
  "rotate-pdf": () => import("@/components/tools/document/RotatePdf"),
  "delete-pdf-pages": () => import("@/components/tools/document/DeletePdfPages"),
  "compress-pdf": () => import("@/components/tools/document/CompressPdf"),
  "word-counter": () => import("@/components/tools/document/WordCounter"),
  "base64-encoder-decoder": () => import("@/components/tools/developer/Base64EncoderDecoder"),
  "url-encoder-decoder": () => import("@/components/tools/developer/UrlEncoderDecoder"),
  "jwt-decoder": () => import("@/components/tools/developer/JwtDecoder"),
  "uuid-generator": () => import("@/components/tools/developer/UuidGenerator"),
  "hash-generator": () => import("@/components/tools/developer/HashGenerator"),
  "regex-tester": () => import("@/components/tools/developer/RegexTester"),
  "markdown-previewer": () => import("@/components/tools/developer/MarkdownPreviewer"),
  "csv-to-json": () => import("@/components/tools/developer/CsvToJson"),
  "lorem-ipsum-generator": () => import("@/components/tools/developer/LoremIpsumGenerator"),
  "percentage-calculator": () => import("@/components/tools/financial/PercentageCalculator"),
  "discount-calculator": () => import("@/components/tools/financial/DiscountCalculator"),
  "tip-calculator": () => import("@/components/tools/financial/TipCalculator"),
  "loan-emi-calculator": () => import("@/components/tools/financial/LoanEmiCalculator"),
  "compound-interest-calculator": () => import("@/components/tools/financial/CompoundInterestCalculator"),
  "sales-tax-calculator": () => import("@/components/tools/financial/SalesTaxCalculator"),
  "bmi-calculator": () => import("@/components/tools/financial/BmiCalculator"),
  "age-calculator": () => import("@/components/tools/financial/AgeCalculator"),
  "unit-converter": () => import("@/components/tools/financial/UnitConverter"),
  "password-generator": () => import("@/components/tools/developer/PasswordGenerator"),
  "text-case-converter": () => import("@/components/tools/developer/TextCaseConverter"),
  "text-diff-checker": () => import("@/components/tools/developer/TextDiffChecker"),
  "image-cropper": () => import("@/components/tools/media/ImageCropper"),
  "pdf-page-numberer": () => import("@/components/tools/document/PdfPageNumberer"),
  "exif-stripper": () => import("@/components/tools/media/ExifStripper"),
  "zero-width-remover": () => import("@/components/tools/developer/ZeroWidthRemover"),
  "hmac-generator": () => import("@/components/tools/developer/HmacGenerator"),
  "json-to-typescript": () => import("@/components/tools/developer/JsonToTypeScript"),
  "json-to-yaml": () => import("@/components/tools/developer/JsonToYaml"),
  "sql-formatter": () => import("@/components/tools/developer/SqlFormatter"),
  "json-to-csv": () => import("@/components/tools/developer/JsonToCsvConverter"),
  "code-minifier": () => import("@/components/tools/developer/CodeMinifier"),
  "html-entity-encoder": () => import("@/components/tools/developer/HtmlEntityEncoder"),
  "title-case-converter": () => import("@/components/tools/developer/TitleCaseConverter"),
  "url-slug-generator": () => import("@/components/tools/developer/UrlSlugGenerator"),
  "opengraph-generator": () => import("@/components/tools/developer/OpenGraphGenerator"),
  "duplicate-line-remover": () => import("@/components/tools/developer/DuplicateLineRemover"),
  "svg-optimizer": () => import("@/components/tools/media/SvgOptimizer"),
  "screen-recorder": () => import("@/components/tools/media/ScreenRecorder"),
  "wcag-contrast-checker": () => import("@/components/tools/media/WcagContrastChecker"),
  "aspect-ratio-calculator": () => import("@/components/tools/financial/AspectRatioCalculator"),
};
