import type { LucideIcon } from "lucide-react";
import {
  Brain,
  Eye,
  Crosshair,
  Music,
  MousePointerClick,
  FlaskConical,
  ChartSpline,
  Divide,
  Grid3x3,
  Variable,
  Sigma,
  ListTodo,
  Clock3,
  NotebookPen,
  Calculator,
  Keyboard,
  Worm,
  Bomb,
  Blocks,
  PersonStanding,
  Wind,
  Puzzle,
  Gamepad2,
  Zap,
  Timer,
  Headphones,
  Layers,
  CalendarClock,
  Flame,
  ImageIcon,
  FileImage,
  Shrink,
  Maximize,
  FileCode2,
  ArrowLeftRight,
  Binary,
  Star,
  QrCode,
  Pipette,
  Scissors,
  Images,
  FilePlus2,
  RotateCw,
  FileMinus2,
  FileArchive,
  AlignLeft,
  Braces,
  Link2,
  KeyRound,
  Fingerprint,
  Hash,
  Regex,
  FileType2,
  FileJson2,
  Type,
  Percent,
  Tag,
  HandCoins,
  Landmark,
  TrendingUp,
  ReceiptText,
  HeartPulse,
  ShieldCheck,
  CaseSensitive,
  GitCompareArrows,
  Cake,
  Ruler,
  Crop,
  EyeOff,
  Sparkles,
  Database,
  FileSpreadsheet,
  Minimize,
  Code2,
  Heading,
  Share2,
  ListFilter,
  Shapes,
  Video,
  Contrast,
  Proportions,
  Film,
  Mic,
  Laptop,
  PenTool,
  SlidersHorizontal,
  Stamp,
  FileSearch,
  FileOutput,
  PenLine,
  LayoutGrid,
  VolumeX,
  Gauge,
  Home,
  BadgePercent,
  GraduationCap,
  Coins,
  Activity,
  CalendarDays,
  LineChart,
  Wallet,
  Users,
  UserCheck,
  Dices,
  HelpCircle,
  Coins as CoinsIcon,
  Shuffle,
  Trophy,
  Ticket,
  CircleDot,
  Tv,
  Table2,
  Sheet,
  Combine,
  Split,
  Columns3,
  FileDiff,
  Presentation,
  FileText,
} from "lucide-react";

export const CATEGORIES = [
  "media",
  "document",
  "developer",
  "financial",
  "random-decision",
  "focus-study",
  "math-calculators",
] as const;

export type ToolCategory = (typeof CATEGORIES)[number];

/**
 * Structural category metadata only. Translatable label/description strings
 * live in messages/[locale].json under `categories.<slug>` instead.
 */
export interface CategoryMeta {
  slug: ToolCategory;
}

export const CATEGORY_META: Record<ToolCategory, CategoryMeta> = {
  media: { slug: "media" },
  document: { slug: "document" },
  developer: { slug: "developer" },
  financial: { slug: "financial" },
  "random-decision": { slug: "random-decision" },
  "focus-study": { slug: "focus-study" },
  "math-calculators": { slug: "math-calculators" },
};

export interface HowToStep {
  name: string;
  text: string;
}

export interface FaqItem {
  question: string;
  answer: string;
}

export interface ComparisonRow {
  label: string;
  values: string[];
}

export interface ComparisonTableData {
  columns: string[];
  rows: ComparisonRow[];
}

/**
 * Structural / English-source-of-truth fields only. All translatable copy
 * (seoTitle, metaDescription, h1, subheading, keywords, howTo, faq,
 * comparisonTable) lives in messages/[locale].json under `tools.<slug>`
 * instead — see lib/tool-content.ts.
 *
 * `name`/`shortName` are a deliberate exception: they stay here as
 * English-only internal/fallback labels (used e.g. in SiteFooter columns
 * and ToolGrid's slug-based search fallback), not fully localized. This is
 * an explicit scoping choice, not an oversight.
 *
 * Deliberately excludes the tool's actual component/loader: that lives in
 * config/tool-components.ts instead, imported only by the tool detail route.
 * Every other consumer of this file (BentoToolGrid, RecentToolsShelf,
 * CommandMenu, SiteHeader, ToolGrid, ...) only ever needs this lightweight
 * metadata, so keeping the two separate stops those client bundles from
 * pulling in every tool's dynamic-import graph (some of which — pdf-lib,
 * pdfjs-dist, @monaco-editor/react — are large).
 */
export interface ToolConfig {
  slug: string;
  category: ToolCategory;
  icon: LucideIcon;
  name: string;
  shortName: string;
  relatedSlugs: string[];
  /**
   * Set to false only for tools whose initial render is inherently
   * non-deterministic (e.g. generates random values on mount), to avoid
   * server/client hydration mismatches. Defaults to true (SSR enabled).
   */
  ssr?: boolean;
  /**
   * "workspace" gives the tool a wide, viewport-tall layout (editors, split panes).
   * Defaults to the standard narrow layout.
   */
  layout?: "default" | "workspace";
  /** Pinned first in its category and shown as a highlighted banner card. */
  featured?: boolean;
  /** Sub-section on the category page (only used by the Focus & Games category). */
  group?: "study" | "relax" | "train" | "fun";
  priority: number;
  changeFrequency: "daily" | "weekly" | "monthly";
}

export const TOOLS: ToolConfig[] = [
  {
    slug: "jpg-to-png",
    category: "media",
    icon: ImageIcon,
    name: "JPG to PNG Converter",
    shortName: "JPG to PNG",
    relatedSlugs: ["merge-pdf", "json-formatter"],
    priority: 1,
    changeFrequency: "weekly",
  },
  {
    slug: "merge-pdf",
    category: "document",
    icon: FilePlus2,
    name: "Merge PDF Files",
    shortName: "Merge PDF",
    relatedSlugs: ["jpg-to-png", "json-formatter"],
    priority: 1,
    changeFrequency: "weekly",
  },
  {
    slug: "json-formatter",
    category: "developer",
    icon: Braces,
    name: "JSON Formatter & Validator",
    shortName: "JSON Formatter",
    relatedSlugs: ["jpg-to-png", "salary-to-hourly"],
    layout: "workspace",
    priority: 1,
    changeFrequency: "weekly",
  },
  {
    slug: "salary-to-hourly",
    category: "financial",
    icon: Landmark,
    name: "Salary to Hourly Calculator",
    shortName: "Salary to Hourly",
    relatedSlugs: ["json-formatter", "merge-pdf"],
    priority: 0.78,
    changeFrequency: "monthly",
  },

  // ---------------------------------------------------------------------
  // Media
  // ---------------------------------------------------------------------
  {
    slug: "heic-to-jpg",
    category: "media",
    icon: FileImage,
    name: "HEIC to JPG Converter",
    shortName: "HEIC to JPG",
    relatedSlugs: ["jpg-to-png", "image-compressor"],
    priority: 0.92,
    changeFrequency: "weekly",
  },
  {
    slug: "image-compressor",
    category: "media",
    icon: Shrink,
    name: "Image Compressor",
    shortName: "Image Compressor",
    relatedSlugs: ["image-resizer", "webp-converter"],
    priority: 0.94,
    changeFrequency: "weekly",
    layout: "workspace",
  },
  {
    slug: "image-resizer",
    category: "media",
    icon: Maximize,
    name: "Image Resizer",
    shortName: "Image Resizer",
    relatedSlugs: ["image-compressor", "favicon-generator"],
    priority: 0.84,
    changeFrequency: "weekly",
  },
  {
    slug: "webp-converter",
    category: "media",
    icon: FileCode2,
    name: "Image to WebP Converter",
    shortName: "WebP Converter",
    relatedSlugs: ["image-compressor", "png-to-jpg"],
    priority: 0.8,
    changeFrequency: "weekly",
  },
  {
    slug: "png-to-jpg",
    category: "media",
    icon: ArrowLeftRight,
    name: "PNG to JPG Converter",
    shortName: "PNG to JPG",
    relatedSlugs: ["jpg-to-png", "image-compressor"],
    priority: 0.96,
    changeFrequency: "weekly",
    layout: "workspace",
  },
  {
    slug: "svg-to-png",
    category: "media",
    icon: Shapes,
    name: "SVG to PNG Converter",
    shortName: "SVG to PNG",
    relatedSlugs: ["svg-optimizer", "png-to-jpg"],
    priority: 0.82,
    changeFrequency: "weekly",
    layout: "workspace",
  },
  {
    slug: "svg-to-jpg",
    category: "media",
    icon: Shapes,
    name: "SVG to JPG Converter",
    shortName: "SVG to JPG",
    relatedSlugs: ["svg-to-png", "jpg-to-png"],
    priority: 0.74,
    changeFrequency: "weekly",
    layout: "workspace",
  },
  {
    slug: "svg-to-webp",
    category: "media",
    icon: Shapes,
    name: "SVG to WebP Converter",
    shortName: "SVG to WebP",
    relatedSlugs: ["svg-to-png", "webp-converter"],
    priority: 0.7,
    changeFrequency: "weekly",
    layout: "workspace",
  },
  {
    slug: "png-to-webp",
    category: "media",
    icon: ArrowLeftRight,
    name: "PNG to WebP Converter",
    shortName: "PNG to WebP",
    relatedSlugs: ["webp-converter", "jpg-to-png"],
    priority: 0.78,
    changeFrequency: "weekly",
    layout: "workspace",
  },
  {
    slug: "webp-to-png",
    category: "media",
    icon: ArrowLeftRight,
    name: "WebP to PNG Converter",
    shortName: "WebP to PNG",
    relatedSlugs: ["png-to-jpg", "webp-converter"],
    priority: 0.78,
    changeFrequency: "weekly",
    layout: "workspace",
  },
  {
    slug: "webp-to-jpg",
    category: "media",
    icon: ArrowLeftRight,
    name: "WebP to JPG Converter",
    shortName: "WebP to JPG",
    relatedSlugs: ["png-to-jpg", "webp-converter"],
    priority: 0.76,
    changeFrequency: "weekly",
    layout: "workspace",
  },
  {
    slug: "jpg-to-webp",
    category: "media",
    icon: ArrowLeftRight,
    name: "JPG to WebP Converter",
    shortName: "JPG to WebP",
    relatedSlugs: ["webp-converter", "png-to-jpg"],
    priority: 0.76,
    changeFrequency: "weekly",
    layout: "workspace",
  },
  {
    slug: "base64-image-encoder",
    category: "media",
    icon: Binary,
    name: "Base64 Image Encoder",
    shortName: "Base64 Image Encoder",
    relatedSlugs: ["qr-code-generator", "json-formatter"],
    priority: 0.65,
    changeFrequency: "monthly",
  },
  {
    slug: "favicon-generator",
    category: "media",
    icon: Star,
    name: "Favicon Generator",
    shortName: "Favicon Generator",
    relatedSlugs: ["image-resizer", "qr-code-generator"],
    priority: 0.7,
    changeFrequency: "monthly",
  },
  {
    slug: "qr-code-generator",
    category: "media",
    icon: QrCode,
    name: "QR Code Generator",
    shortName: "QR Code Generator",
    relatedSlugs: ["base64-image-encoder", "favicon-generator"],
    ssr: false,
    layout: "workspace",
    priority: 0.98,
    changeFrequency: "weekly",
  },
  {
    slug: "color-picker",
    category: "media",
    icon: Pipette,
    name: "Image Color Picker",
    shortName: "Color Picker",
    relatedSlugs: ["qr-code-generator", "favicon-generator"],
    layout: "workspace",
    priority: 0.68,
    changeFrequency: "monthly",
  },

  // ---------------------------------------------------------------------
  // Document
  // ---------------------------------------------------------------------
  {
    slug: "split-pdf",
    category: "document",
    icon: Scissors,
    name: "Split PDF Files",
    shortName: "Split PDF",
    relatedSlugs: ["merge-pdf", "delete-pdf-pages"],
    priority: 0.94,
    changeFrequency: "weekly",
  },
  {
    slug: "pdf-to-images",
    category: "document",
    icon: FileImage,
    name: "PDF to Images Converter",
    shortName: "PDF to Images",
    relatedSlugs: ["images-to-pdf", "split-pdf"],
    priority: 0.88,
    changeFrequency: "weekly",
  },
  {
    slug: "images-to-pdf",
    category: "document",
    icon: Images,
    name: "Images to PDF Converter",
    shortName: "Images to PDF",
    relatedSlugs: ["pdf-to-images", "merge-pdf"],
    priority: 0.86,
    changeFrequency: "weekly",
  },
  {
    slug: "rotate-pdf",
    category: "document",
    icon: RotateCw,
    name: "Rotate PDF Pages",
    shortName: "Rotate PDF",
    relatedSlugs: ["split-pdf", "delete-pdf-pages"],
    priority: 0.76,
    changeFrequency: "weekly",
  },
  {
    slug: "delete-pdf-pages",
    category: "document",
    icon: FileMinus2,
    name: "Delete PDF Pages",
    shortName: "Delete PDF Pages",
    relatedSlugs: ["split-pdf", "rotate-pdf"],
    priority: 0.78,
    changeFrequency: "weekly",
  },
  {
    slug: "compress-pdf",
    category: "document",
    icon: FileArchive,
    name: "Compress PDF Files",
    shortName: "Compress PDF",
    relatedSlugs: ["merge-pdf", "split-pdf"],
    priority: 0.9,
    changeFrequency: "weekly",
  },
  {
    slug: "word-counter",
    category: "document",
    icon: AlignLeft,
    name: "Word & Character Counter",
    shortName: "Word Counter",
    relatedSlugs: ["markdown-previewer", "lorem-ipsum-generator"],
    priority: 0.82,
    changeFrequency: "monthly",
  },

  // ---------------------------------------------------------------------
  // Developer
  // ---------------------------------------------------------------------
  {
    slug: "base64-encoder-decoder",
    category: "developer",
    icon: Binary,
    name: "Base64 Encoder / Decoder",
    shortName: "Base64 Encoder",
    relatedSlugs: ["url-encoder-decoder", "jwt-decoder"],
    layout: "workspace",
    priority: 0.92,
    changeFrequency: "weekly",
  },
  {
    slug: "url-encoder-decoder",
    category: "developer",
    icon: Link2,
    name: "URL Encoder / Decoder",
    shortName: "URL Encoder",
    relatedSlugs: ["base64-encoder-decoder", "jwt-decoder"],
    layout: "workspace",
    priority: 0.83,
    changeFrequency: "weekly",
  },
  {
    slug: "jwt-decoder",
    category: "developer",
    icon: KeyRound,
    name: "JWT Decoder",
    shortName: "JWT Decoder",
    relatedSlugs: ["base64-encoder-decoder", "hash-generator"],
    ssr: false,
    priority: 0.87,
    changeFrequency: "weekly",
  },
  {
    slug: "uuid-generator",
    category: "developer",
    icon: Fingerprint,
    name: "UUID Generator",
    shortName: "UUID Generator",
    relatedSlugs: ["hash-generator", "jwt-decoder"],
    ssr: false,
    priority: 0.9,
    changeFrequency: "weekly",
  },
  {
    slug: "hash-generator",
    category: "developer",
    icon: Hash,
    name: "Hash Generator (SHA-1/256/384/512)",
    shortName: "Hash Generator",
    relatedSlugs: ["uuid-generator", "jwt-decoder"],
    priority: 0.9,
    changeFrequency: "weekly",
  },
  {
    slug: "regex-tester",
    category: "developer",
    icon: Regex,
    name: "Regex Tester",
    shortName: "Regex Tester",
    relatedSlugs: ["json-formatter", "csv-to-json"],
    layout: "workspace",
    priority: 0.84,
    changeFrequency: "weekly",
  },
  {
    slug: "markdown-previewer",
    category: "developer",
    icon: FileType2,
    name: "Markdown Previewer",
    shortName: "Markdown Previewer",
    relatedSlugs: ["word-counter", "json-formatter"],
    ssr: false,
    layout: "workspace",
    priority: 0.78,
    changeFrequency: "weekly",
  },
  {
    slug: "csv-to-json",
    category: "developer",
    icon: FileJson2,
    name: "CSV to JSON Converter",
    shortName: "CSV to JSON",
    relatedSlugs: ["json-formatter", "regex-tester"],
    layout: "workspace",
    priority: 0.79,
    changeFrequency: "weekly",
  },
  {
    slug: "lorem-ipsum-generator",
    category: "developer",
    icon: Type,
    name: "Lorem Ipsum Generator",
    shortName: "Lorem Ipsum",
    relatedSlugs: ["word-counter", "markdown-previewer"],
    ssr: false,
    layout: "workspace",
    priority: 0.62,
    changeFrequency: "monthly",
  },

  // ---------------------------------------------------------------------
  // Financial
  // ---------------------------------------------------------------------
  {
    slug: "percentage-calculator",
    category: "financial",
    icon: Percent,
    name: "Percentage Calculator",
    shortName: "Percentage Calculator",
    relatedSlugs: ["discount-calculator", "sales-tax-calculator"],
    priority: 0.99,
    changeFrequency: "monthly",
  },
  {
    slug: "discount-calculator",
    category: "financial",
    icon: Tag,
    name: "Discount Calculator",
    shortName: "Discount Calculator",
    relatedSlugs: ["percentage-calculator", "sales-tax-calculator"],
    priority: 0.92,
    changeFrequency: "monthly",
  },
  {
    slug: "tip-calculator",
    category: "financial",
    icon: HandCoins,
    name: "Tip Calculator",
    shortName: "Tip Calculator",
    relatedSlugs: ["percentage-calculator", "sales-tax-calculator"],
    priority: 0.95,
    changeFrequency: "monthly",
  },
  {
    slug: "loan-emi-calculator",
    category: "financial",
    icon: Landmark,
    name: "Loan EMI Calculator",
    shortName: "Loan EMI Calculator",
    relatedSlugs: ["compound-interest-calculator", "salary-to-hourly"],
    priority: 0.83,
    changeFrequency: "monthly",
  },
  {
    slug: "compound-interest-calculator",
    category: "financial",
    icon: TrendingUp,
    name: "Compound Interest Calculator",
    shortName: "Compound Interest",
    relatedSlugs: ["loan-emi-calculator", "percentage-calculator"],
    priority: 0.72,
    changeFrequency: "monthly",
  },
  {
    slug: "sales-tax-calculator",
    category: "financial",
    icon: ReceiptText,
    name: "Sales Tax Calculator",
    shortName: "Sales Tax Calculator",
    relatedSlugs: ["discount-calculator", "tip-calculator"],
    priority: 0.76,
    changeFrequency: "monthly",
  },
  {
    slug: "bmi-calculator",
    category: "financial",
    icon: HeartPulse,
    name: "BMI Calculator",
    shortName: "BMI Calculator",
    relatedSlugs: ["percentage-calculator", "salary-to-hourly"],
    priority: 0.93,
    changeFrequency: "monthly",
  },
  {
    slug: "age-calculator",
    category: "financial",
    icon: Cake,
    name: "Age Calculator",
    shortName: "Age Calculator",
    relatedSlugs: ["bmi-calculator", "percentage-calculator"],
    priority: 0.88,
    changeFrequency: "monthly",
  },
  {
    slug: "unit-converter",
    category: "financial",
    icon: Ruler,
    name: "Unit Converter",
    shortName: "Unit Converter",
    relatedSlugs: ["percentage-calculator", "bmi-calculator"],
    priority: 0.87,
    changeFrequency: "monthly",
  },
  {
    slug: "mortgage-calculator",
    category: "financial",
    icon: Home,
    name: "Mortgage Calculator",
    shortName: "Mortgage Calculator",
    relatedSlugs: ["loan-emi-calculator", "compound-interest-calculator"],
    priority: 0.86,
    changeFrequency: "monthly",
  },
  {
    slug: "simple-interest-calculator",
    category: "financial",
    icon: BadgePercent,
    name: "Simple Interest Calculator",
    shortName: "Simple Interest",
    relatedSlugs: ["compound-interest-calculator", "loan-emi-calculator"],
    priority: 0.7,
    changeFrequency: "monthly",
  },
  {
    slug: "gpa-calculator",
    category: "financial",
    icon: GraduationCap,
    name: "GPA Calculator",
    shortName: "GPA Calculator",
    relatedSlugs: ["percentage-calculator", "age-calculator"],
    priority: 0.75,
    changeFrequency: "monthly",
  },
  {
    slug: "currency-converter",
    category: "financial",
    icon: Coins,
    name: "Currency Converter",
    shortName: "Currency Converter",
    relatedSlugs: ["unit-converter", "percentage-calculator"],
    priority: 0.9,
    changeFrequency: "daily",
  },
  {
    slug: "body-fat-calculator",
    category: "financial",
    icon: Activity,
    name: "Body Fat Calculator",
    shortName: "Body Fat Calculator",
    relatedSlugs: ["bmi-calculator", "age-calculator"],
    priority: 0.73,
    changeFrequency: "monthly",
  },
  {
    slug: "date-difference-calculator",
    category: "financial",
    icon: CalendarDays,
    name: "Date Difference Calculator",
    shortName: "Date Difference",
    relatedSlugs: ["age-calculator", "percentage-calculator"],
    priority: 0.78,
    changeFrequency: "monthly",
  },
  {
    slug: "investment-return-calculator",
    category: "financial",
    icon: LineChart,
    name: "Investment Return Calculator",
    shortName: "Investment Return",
    relatedSlugs: ["compound-interest-calculator", "mortgage-calculator"],
    priority: 0.74,
    changeFrequency: "monthly",
  },
  {
    slug: "paycheck-calculator",
    category: "financial",
    icon: Wallet,
    name: "Paycheck Calculator",
    shortName: "Paycheck Calculator",
    relatedSlugs: ["salary-to-hourly", "sales-tax-calculator"],
    priority: 0.8,
    changeFrequency: "monthly",
  },

  // ---------------------------------------------------------------------
  // Developer (new)
  // ---------------------------------------------------------------------
  {
    slug: "password-generator",
    category: "developer",
    icon: ShieldCheck,
    name: "Password Generator",
    shortName: "Password Generator",
    relatedSlugs: ["hash-generator", "uuid-generator"],
    ssr: false,
    priority: 0.95,
    changeFrequency: "weekly",
  },
  {
    slug: "text-case-converter",
    category: "developer",
    icon: CaseSensitive,
    name: "Text Case Converter",
    shortName: "Case Converter",
    relatedSlugs: ["word-counter", "lorem-ipsum-generator"],
    layout: "workspace",
    priority: 0.86,
    changeFrequency: "weekly",
  },
  {
    slug: "text-diff-checker",
    category: "developer",
    icon: GitCompareArrows,
    name: "Text Diff Checker",
    shortName: "Diff Checker",
    relatedSlugs: ["json-formatter", "text-case-converter"],
    layout: "workspace",
    priority: 0.81,
    changeFrequency: "weekly",
  },

  // ---------------------------------------------------------------------
  // Media (new)
  // ---------------------------------------------------------------------
  {
    slug: "image-cropper",
    category: "media",
    icon: Crop,
    name: "Image Cropper",
    shortName: "Image Cropper",
    relatedSlugs: ["image-resizer", "image-compressor"],
    layout: "workspace",
    priority: 0.89,
    changeFrequency: "weekly",
  },

  // ---------------------------------------------------------------------
  // Document (new)
  // ---------------------------------------------------------------------
  {
    slug: "pdf-page-numberer",
    category: "document",
    icon: Hash,
    name: "PDF Page Numberer",
    shortName: "Page Numberer",
    relatedSlugs: ["merge-pdf", "rotate-pdf"],
    priority: 0.73,
    changeFrequency: "weekly",
  },

  // ---------------------------------------------------------------------
  // Document — Office conversions (new)
  // ---------------------------------------------------------------------
  {
    slug: "pdf-maker",
    category: "document",
    icon: FileOutput,
    name: "PDF Maker — Word, Excel, Text & HTML to PDF",
    shortName: "PDF Maker",
    relatedSlugs: ["word-maker", "spreadsheet-converter"],
    ssr: false,
    layout: "workspace",
    priority: 0.92,
    changeFrequency: "weekly",
  },
  {
    slug: "spreadsheet-converter",
    category: "document",
    icon: FileSpreadsheet,
    name: "Spreadsheet Converter — Excel, CSV, JSON & More",
    shortName: "Spreadsheet Converter",
    relatedSlugs: ["spreadsheet-studio", "pdf-maker"],
    ssr: false,
    priority: 0.9,
    changeFrequency: "weekly",
  },
  {
    slug: "word-maker",
    category: "document",
    icon: FileText,
    name: "Word Document Maker with Templates",
    shortName: "Word Maker",
    relatedSlugs: ["word-converter", "pdf-maker"],
    ssr: false,
    priority: 0.86,
    changeFrequency: "weekly",
  },
  {
    slug: "spreadsheet-studio",
    category: "document",
    icon: Sheet,
    name: "Spreadsheet Editor, Cleaner & Merger",
    shortName: "Spreadsheet Studio",
    relatedSlugs: ["spreadsheet-converter", "pdf-maker"],
    ssr: false,
    priority: 0.84,
    changeFrequency: "weekly",
  },
  {
    slug: "word-converter",
    category: "document",
    icon: FileCode2,
    name: "Word to HTML, Markdown & Text Converter",
    shortName: "Word Converter",
    relatedSlugs: ["word-maker", "pdf-maker"],
    ssr: false,
    priority: 0.82,
    changeFrequency: "weekly",
  },
  {
    slug: "watermark-pdf",
    category: "document",
    icon: Stamp,
    name: "Add Watermark to PDF",
    shortName: "PDF Watermark",
    relatedSlugs: ["pdf-page-numberer", "merge-pdf"],
    ssr: false,
    priority: 0.8,
    changeFrequency: "weekly",
  },
  {
    slug: "pdf-to-text",
    category: "document",
    icon: FileType2,
    name: "PDF to Text Converter",
    shortName: "PDF to Text",
    relatedSlugs: ["pdf-maker", "word-converter"],
    ssr: false,
    priority: 0.8,
    changeFrequency: "weekly",
  },
  {
    slug: "organize-pdf",
    category: "document",
    icon: LayoutGrid,
    name: "Organize PDF Pages",
    shortName: "Organize PDF",
    relatedSlugs: ["merge-pdf", "split-pdf", "rotate-pdf"],
    ssr: false,
    layout: "workspace",
    priority: 0.86,
    changeFrequency: "weekly",
  },
  {
    slug: "sign-pdf",
    category: "document",
    icon: PenLine,
    name: "Sign PDF Online",
    shortName: "Sign PDF",
    relatedSlugs: ["pdf-maker", "watermark-pdf", "crop-pdf"],
    ssr: false,
    layout: "workspace",
    priority: 0.88,
    changeFrequency: "weekly",
  },
  {
    slug: "crop-pdf",
    category: "document",
    icon: Crop,
    name: "Crop PDF Pages",
    shortName: "Crop PDF",
    relatedSlugs: ["organize-pdf", "rotate-pdf", "compress-pdf"],
    ssr: false,
    layout: "workspace",
    priority: 0.8,
    changeFrequency: "weekly",
  },
  {
    slug: "pdf-metadata",
    category: "document",
    icon: FileSearch,
    name: "PDF Metadata Editor",
    shortName: "PDF Metadata",
    relatedSlugs: ["compress-pdf", "sign-pdf", "pdf-to-text"],
    ssr: false,
    priority: 0.72,
    changeFrequency: "monthly",
  },
  {
    slug: "pdf-to-word",
    category: "document",
    icon: FileOutput,
    name: "PDF to Word Converter",
    shortName: "PDF to Word",
    relatedSlugs: ["pdf-to-text", "word-maker", "pdf-maker"],
    ssr: false,
    layout: "workspace",
    priority: 0.9,
    changeFrequency: "weekly",
  },
  {
    slug: "powerpoint-maker",
    category: "document",
    icon: Presentation,
    name: "PowerPoint Maker with Templates",
    shortName: "PowerPoint Maker",
    relatedSlugs: ["word-maker", "pdf-maker"],
    ssr: false,
    priority: 0.86,
    changeFrequency: "weekly",
  },

  // ---------------------------------------------------------------------
  // Privacy & Security (new)
  // ---------------------------------------------------------------------
  {
    slug: "exif-stripper",
    category: "media",
    icon: EyeOff,
    name: "EXIF & GPS Metadata Remover",
    shortName: "EXIF Remover",
    relatedSlugs: ["image-compressor", "image-cropper"],
    priority: 0.85,
    changeFrequency: "weekly",
  },
  {
    slug: "zero-width-remover",
    category: "developer",
    icon: Sparkles,
    name: "Zero-Width Space & Invisible Character Cleaner",
    shortName: "Invisible Char Cleaner",
    relatedSlugs: ["text-diff-checker", "html-entity-encoder"],
    layout: "workspace",
    priority: 0.66,
    changeFrequency: "weekly",
  },
  {
    slug: "hmac-generator",
    category: "developer",
    icon: KeyRound,
    name: "HMAC Keyed-Hash Generator",
    shortName: "HMAC Generator",
    relatedSlugs: ["hash-generator", "password-generator"],
    priority: 0.72,
    changeFrequency: "weekly",
  },

  // ---------------------------------------------------------------------
  // Developer & Code Utilities (new)
  // ---------------------------------------------------------------------
  {
    slug: "json-to-typescript",
    category: "developer",
    icon: Braces,
    name: "JSON to TypeScript & Zod Schema",
    shortName: "JSON to TS",
    relatedSlugs: ["json-formatter", "json-to-yaml"],
    layout: "workspace",
    priority: 0.83,
    changeFrequency: "weekly",
  },
  {
    slug: "json-to-yaml",
    category: "developer",
    icon: FileCode2,
    name: "JSON ↔ YAML Converter",
    shortName: "JSON ↔ YAML",
    relatedSlugs: ["json-formatter", "json-to-typescript"],
    layout: "workspace",
    priority: 0.8,
    changeFrequency: "weekly",
  },
  {
    slug: "sql-formatter",
    category: "developer",
    icon: Database,
    name: "SQL Query Formatter",
    shortName: "SQL Formatter",
    relatedSlugs: ["json-formatter", "code-minifier"],
    layout: "workspace",
    priority: 0.78,
    changeFrequency: "weekly",
  },
  {
    slug: "json-to-csv",
    category: "developer",
    icon: FileSpreadsheet,
    name: "JSON to CSV Converter",
    shortName: "JSON to CSV",
    relatedSlugs: ["json-formatter", "csv-to-json"],
    layout: "workspace",
    priority: 0.75,
    changeFrequency: "weekly",
  },
  {
    slug: "code-minifier",
    category: "developer",
    icon: Minimize,
    name: "HTML & CSS Minifier",
    shortName: "Code Minifier",
    relatedSlugs: ["sql-formatter", "json-formatter"],
    layout: "workspace",
    priority: 0.74,
    changeFrequency: "weekly",
  },
  {
    slug: "html-entity-encoder",
    category: "developer",
    icon: Code2,
    name: "HTML Entity Encoder / Decoder",
    shortName: "HTML Entity Encoder",
    relatedSlugs: ["url-encoder-decoder", "base64-encoder-decoder"],
    layout: "workspace",
    priority: 0.71,
    changeFrequency: "weekly",
  },

  // ---------------------------------------------------------------------
  // Content Creators & SEO Tools (new)
  // ---------------------------------------------------------------------
  {
    slug: "title-case-converter",
    category: "developer",
    icon: Heading,
    name: "Title Case & Headline Capitalizer",
    shortName: "Title Case Converter",
    relatedSlugs: ["text-case-converter", "url-slug-generator"],
    layout: "workspace",
    priority: 0.77,
    changeFrequency: "weekly",
  },
  {
    slug: "url-slug-generator",
    category: "developer",
    icon: Link2,
    name: "SEO URL Slug Generator",
    shortName: "Slug Generator",
    relatedSlugs: ["title-case-converter", "opengraph-generator"],
    layout: "workspace",
    priority: 0.82,
    changeFrequency: "weekly",
  },
  {
    slug: "opengraph-generator",
    category: "developer",
    icon: Share2,
    name: "OpenGraph & Meta Tag Generator",
    shortName: "OpenGraph Generator",
    relatedSlugs: ["url-slug-generator", "title-case-converter"],
    priority: 0.86,
    changeFrequency: "weekly",
  },
  {
    slug: "duplicate-line-remover",
    category: "developer",
    icon: ListFilter,
    name: "Duplicate Line Remover & List Sorter",
    shortName: "Duplicate Line Remover",
    relatedSlugs: ["text-case-converter", "word-counter"],
    layout: "workspace",
    priority: 0.7,
    changeFrequency: "weekly",
  },

  // ---------------------------------------------------------------------
  // Media & Design Utilities (new)
  // ---------------------------------------------------------------------
  {
    slug: "svg-optimizer",
    category: "media",
    icon: Shapes,
    name: "SVG Optimizer & Path Cleaner",
    shortName: "SVG Optimizer",
    relatedSlugs: ["image-compressor", "code-minifier"],
    priority: 0.76,
    changeFrequency: "weekly",
  },
  {
    slug: "screen-recorder",
    category: "media",
    icon: Video,
    name: "In-Browser Screen & Audio Recorder",
    shortName: "Screen Recorder",
    relatedSlugs: ["image-cropper", "image-compressor"],
    ssr: false,
    priority: 0.81,
    changeFrequency: "weekly",
  },
  {
    slug: "wcag-contrast-checker",
    category: "media",
    icon: Contrast,
    name: "WCAG Color Contrast Checker",
    shortName: "Contrast Checker",
    relatedSlugs: ["color-picker", "svg-optimizer"],
    priority: 0.73,
    changeFrequency: "weekly",
  },
  {
    slug: "aspect-ratio-calculator",
    category: "financial",
    icon: Proportions,
    name: "Aspect Ratio & Dimension Calculator",
    shortName: "Aspect Ratio Calculator",
    relatedSlugs: ["unit-converter", "image-resizer"],
    priority: 0.69,
    changeFrequency: "weekly",
  },

  // ---------------------------------------------------------------------
  // Media Capture & Creative Studio Suite
  // ---------------------------------------------------------------------
  {
    slug: "screen-studio",
    category: "media",
    icon: Video,
    name: "Screen & Webcam Studio Recorder",
    shortName: "Screen Studio",
    relatedSlugs: ["screen-recorder", "video-trimmer"],
    ssr: false,
    priority: 0.82,
    changeFrequency: "weekly",
  },
  {
    slug: "screen-to-gif",
    category: "media",
    icon: Film,
    name: "Screen to Animated GIF",
    shortName: "Screen to GIF",
    relatedSlugs: ["screen-studio", "video-to-gif"],
    ssr: false,
    priority: 0.75,
    changeFrequency: "weekly",
  },
  {
    slug: "audio-recorder",
    category: "media",
    icon: Mic,
    name: "Voice & Audio Memo Recorder",
    shortName: "Audio Recorder",
    relatedSlugs: ["screen-studio", "video-audio-remover"],
    ssr: false,
    priority: 0.74,
    changeFrequency: "weekly",
  },
  {
    slug: "screenshot-beautifier",
    category: "media",
    icon: Laptop,
    name: "Screenshot Beautifier & Frame Mockup",
    shortName: "Screenshot Beautifier",
    relatedSlugs: ["image-annotator", "image-cropper"],
    layout: "workspace",
    priority: 0.83,
    changeFrequency: "weekly",
  },
  {
    slug: "image-annotator",
    category: "media",
    icon: PenTool,
    name: "Image Annotator & Pixelate Redactor",
    shortName: "Image Annotator",
    relatedSlugs: ["screenshot-beautifier", "image-cropper"],
    layout: "workspace",
    priority: 0.83,
    changeFrequency: "weekly",
  },
  {
    slug: "image-filters",
    category: "media",
    icon: SlidersHorizontal,
    name: "Canvas Image Filters & Color Grading",
    shortName: "Image Filters",
    relatedSlugs: ["image-annotator", "image-compressor"],
    layout: "workspace",
    priority: 0.78,
    changeFrequency: "weekly",
  },
  {
    slug: "watermark-maker",
    category: "media",
    icon: Stamp,
    name: "Batch Image Watermarker",
    shortName: "Watermark Maker",
    relatedSlugs: ["image-collage", "image-compressor"],
    layout: "workspace",
    priority: 0.78,
    changeFrequency: "weekly",
  },
  {
    slug: "image-collage",
    category: "media",
    icon: LayoutGrid,
    name: "Collage Maker & Photo Grid",
    shortName: "Collage Maker",
    relatedSlugs: ["watermark-maker", "image-cropper"],
    layout: "workspace",
    priority: 0.77,
    changeFrequency: "weekly",
  },
  {
    slug: "video-trimmer",
    category: "media",
    icon: Scissors,
    name: "Video Trimmer & Cutter",
    shortName: "Video Trimmer",
    relatedSlugs: ["video-to-gif", "video-speed"],
    ssr: false,
    layout: "workspace",
    priority: 0.85,
    changeFrequency: "weekly",
  },
  {
    slug: "video-to-gif",
    category: "media",
    icon: Sparkles,
    name: "Video to GIF Converter",
    shortName: "Video to GIF",
    relatedSlugs: ["video-trimmer", "screen-to-gif"],
    ssr: false,
    layout: "workspace",
    priority: 0.8,
    changeFrequency: "weekly",
  },
  {
    slug: "video-audio-remover",
    category: "media",
    icon: VolumeX,
    name: "Video Muter & Audio Extractor",
    shortName: "Audio Remover",
    relatedSlugs: ["video-trimmer", "audio-recorder"],
    ssr: false,
    layout: "workspace",
    priority: 0.76,
    changeFrequency: "weekly",
  },
  {
    slug: "video-speed",
    category: "media",
    icon: Gauge,
    name: "Video Speed Controller (Slow-Mo & Fast)",
    shortName: "Video Speed",
    relatedSlugs: ["video-trimmer", "video-to-gif"],
    ssr: false,
    layout: "workspace",
    priority: 0.76,
    changeFrequency: "weekly",
  },
  {
    slug: "iptv-player",
    category: "media",
    icon: Tv,
    name: "Free IPTV Live TV Player",
    shortName: "IPTV Player",
    relatedSlugs: ["screen-studio", "video-trimmer"],
    ssr: false,
    layout: "workspace",
    featured: true,
    priority: 0.78,
    changeFrequency: "daily",
  },

  // ---------------------------------------------------------------------
  // Random & Decision
  // ---------------------------------------------------------------------
  {
    slug: "team-generator",
    category: "random-decision",
    icon: Users,
    name: "Team Generator",
    shortName: "Team Generator",
    relatedSlugs: ["random-name-picker", "list-shuffler"],
    priority: 0.7,
    changeFrequency: "monthly",
  },
  {
    slug: "wheel-spinner",
    category: "random-decision",
    icon: CircleDot,
    name: "Random Wheel Spinner",
    shortName: "Wheel Spinner",
    relatedSlugs: ["random-name-picker", "yes-no-decision-maker"],
    ssr: false,
    layout: "workspace",
    priority: 0.72,
    changeFrequency: "monthly",
  },
  {
    slug: "random-name-picker",
    category: "random-decision",
    icon: UserCheck,
    name: "Random Name Picker",
    shortName: "Name Picker",
    relatedSlugs: ["team-generator", "wheel-spinner"],
    ssr: false,
    priority: 0.71,
    changeFrequency: "monthly",
  },
  {
    slug: "random-number-generator",
    category: "random-decision",
    icon: Dices,
    name: "Random Number Generator",
    shortName: "Number Generator",
    relatedSlugs: ["dice-roller", "coin-flip"],
    ssr: false,
    priority: 0.68,
    changeFrequency: "monthly",
  },
  {
    slug: "yes-no-decision-maker",
    category: "random-decision",
    icon: HelpCircle,
    name: "Yes or No Decision Maker",
    shortName: "Yes/No Decider",
    relatedSlugs: ["coin-flip", "wheel-spinner"],
    ssr: false,
    priority: 0.65,
    changeFrequency: "monthly",
  },
  {
    slug: "coin-flip",
    category: "random-decision",
    icon: CoinsIcon,
    name: "Coin Flip",
    shortName: "Coin Flip",
    relatedSlugs: ["dice-roller", "yes-no-decision-maker"],
    ssr: false,
    priority: 0.67,
    changeFrequency: "monthly",
  },
  {
    slug: "dice-roller",
    category: "random-decision",
    icon: Dices,
    name: "Dice Roller",
    shortName: "Dice Roller",
    relatedSlugs: ["coin-flip", "random-number-generator"],
    ssr: false,
    priority: 0.66,
    changeFrequency: "monthly",
  },
  {
    slug: "list-shuffler",
    category: "random-decision",
    icon: Shuffle,
    name: "Random List Shuffler",
    shortName: "List Shuffler",
    relatedSlugs: ["team-generator", "random-name-picker"],
    priority: 0.64,
    changeFrequency: "monthly",
  },
  {
    slug: "bracket-generator",
    category: "random-decision",
    icon: Trophy,
    name: "Bracket Generator",
    shortName: "Bracket Generator",
    relatedSlugs: ["team-generator", "list-shuffler"],
    priority: 0.6,
    changeFrequency: "monthly",
  },
  {
    slug: "raffle-picker",
    category: "random-decision",
    icon: Ticket,
    name: "Raffle & Giveaway Picker",
    shortName: "Raffle Picker",
    relatedSlugs: ["random-name-picker", "wheel-spinner"],
    ssr: false,
    priority: 0.63,
    changeFrequency: "monthly",
  },
  {
    slug: "pomodoro-timer",
    category: "focus-study",
    icon: Timer,
    name: "Pomodoro Timer",
    shortName: "Pomodoro Timer",
    relatedSlugs: ["focus-sounds", "stretch-break"],
    ssr: false,
    group: "study",
    priority: 0.8,
    changeFrequency: "monthly",
  },
  {
    slug: "focus-sounds",
    category: "focus-study",
    icon: Headphones,
    name: "Focus Sounds & Noise Mixer",
    shortName: "Focus Sounds",
    relatedSlugs: ["pomodoro-timer", "habit-tracker"],
    ssr: false,
    group: "study",
    priority: 0.76,
    changeFrequency: "monthly",
  },
  {
    slug: "flashcards",
    category: "focus-study",
    icon: Layers,
    name: "Flashcards with Spaced Repetition",
    shortName: "Flashcards",
    relatedSlugs: ["exam-countdown", "pomodoro-timer"],
    ssr: false,
    group: "study",
    priority: 0.74,
    changeFrequency: "monthly",
  },
  {
    slug: "eisenhower-matrix",
    category: "focus-study",
    icon: LayoutGrid,
    name: "Eisenhower Priority Matrix",
    shortName: "Priority Matrix",
    relatedSlugs: ["pomodoro-timer", "habit-tracker"],
    ssr: false,
    group: "study",
    priority: 0.7,
    changeFrequency: "monthly",
  },
  {
    slug: "exam-countdown",
    category: "focus-study",
    icon: CalendarClock,
    name: "Exam & Deadline Countdown",
    shortName: "Exam Countdown",
    relatedSlugs: ["flashcards", "pomodoro-timer"],
    ssr: false,
    group: "study",
    priority: 0.68,
    changeFrequency: "monthly",
  },
  {
    slug: "habit-tracker",
    category: "focus-study",
    icon: Flame,
    name: "Habit & Streak Tracker",
    shortName: "Habit Tracker",
    relatedSlugs: ["pomodoro-timer", "eisenhower-matrix"],
    ssr: false,
    group: "study",
    priority: 0.66,
    changeFrequency: "monthly",
  },
  {
    slug: "stretch-break",
    category: "focus-study",
    icon: PersonStanding,
    name: "Guided Stretch Break",
    shortName: "Stretch Break",
    relatedSlugs: ["breathing-exercise", "pomodoro-timer"],
    ssr: false,
    group: "relax",
    priority: 0.67,
    changeFrequency: "monthly",
  },
  {
    slug: "breathing-exercise",
    category: "focus-study",
    icon: Wind,
    name: "Breathing Exercise & Relaxation Timer",
    shortName: "Breathing Exercise",
    relatedSlugs: ["stretch-break", "focus-sounds"],
    ssr: false,
    group: "relax",
    priority: 0.69,
    changeFrequency: "monthly",
  },
  {
    slug: "memory-match",
    category: "focus-study",
    icon: Puzzle,
    name: "Memory Match Game",
    shortName: "Memory Match",
    relatedSlugs: ["game-2048", "reaction-time-test"],
    ssr: false,
    group: "train",
    priority: 0.62,
    changeFrequency: "monthly",
  },
  {
    slug: "reaction-time-test",
    category: "focus-study",
    icon: Zap,
    name: "Reaction Time Test",
    shortName: "Reaction Time",
    relatedSlugs: ["memory-match", "game-2048"],
    ssr: false,
    group: "train",
    priority: 0.6,
    changeFrequency: "monthly",
  },
  {
    slug: "game-2048",
    category: "focus-study",
    icon: Gamepad2,
    name: "2048 Puzzle Game",
    shortName: "2048 Game",
    relatedSlugs: ["memory-match", "reaction-time-test"],
    ssr: false,
    group: "fun",
    priority: 0.64,
    changeFrequency: "monthly",
  },
  {
    slug: "todo-list",
    category: "focus-study",
    icon: ListTodo,
    name: "To-Do List with Priorities and Due Dates",
    shortName: "To-Do List",
    relatedSlugs: ["eisenhower-matrix", "pomodoro-timer"],
    ssr: false,
    group: "study",
    priority: 0.72,
    changeFrequency: "monthly",
  },
  {
    slug: "study-time-tracker",
    category: "focus-study",
    icon: Clock3,
    name: "Study Time Tracker",
    shortName: "Study Time Tracker",
    relatedSlugs: ["pomodoro-timer", "habit-tracker"],
    ssr: false,
    group: "study",
    priority: 0.71,
    changeFrequency: "monthly",
  },
  {
    slug: "daily-journal",
    category: "focus-study",
    icon: NotebookPen,
    name: "Daily Journal & Mood Tracker",
    shortName: "Daily Journal",
    relatedSlugs: ["habit-tracker", "breathing-exercise"],
    ssr: false,
    group: "study",
    priority: 0.65,
    changeFrequency: "monthly",
  },
  {
    slug: "math-speed-trainer",
    category: "focus-study",
    icon: Calculator,
    name: "Mental Math Speed Trainer",
    shortName: "Math Trainer",
    relatedSlugs: ["typing-speed-test", "memory-match"],
    ssr: false,
    group: "train",
    priority: 0.63,
    changeFrequency: "monthly",
  },
  {
    slug: "typing-speed-test",
    category: "focus-study",
    icon: Keyboard,
    name: "Typing Speed Test",
    shortName: "Typing Test",
    relatedSlugs: ["math-speed-trainer", "reaction-time-test"],
    ssr: false,
    group: "train",
    priority: 0.7,
    changeFrequency: "monthly",
  },
  {
    slug: "snake-game",
    category: "focus-study",
    icon: Worm,
    name: "Snake Game",
    shortName: "Snake Game",
    relatedSlugs: ["game-2048", "memory-match"],
    ssr: false,
    group: "fun",
    priority: 0.61,
    changeFrequency: "monthly",
  },
  {
    slug: "minesweeper",
    category: "focus-study",
    icon: Bomb,
    name: "Minesweeper Game",
    shortName: "Minesweeper",
    relatedSlugs: ["sudoku", "game-2048"],
    ssr: false,
    group: "fun",
    priority: 0.66,
    changeFrequency: "monthly",
  },
  {
    slug: "tic-tac-toe",
    category: "focus-study",
    icon: Hash,
    name: "Tic-Tac-Toe Game",
    shortName: "Tic-Tac-Toe",
    relatedSlugs: ["connect-four", "sudoku"],
    ssr: false,
    group: "fun",
    priority: 0.65,
    changeFrequency: "monthly",
  },
  {
    slug: "connect-four",
    category: "focus-study",
    icon: CircleDot,
    name: "Connect Four Game",
    shortName: "Connect Four",
    relatedSlugs: ["tic-tac-toe", "game-2048"],
    ssr: false,
    group: "fun",
    priority: 0.65,
    changeFrequency: "monthly",
  },
  {
    slug: "sliding-puzzle",
    category: "focus-study",
    icon: Shuffle,
    name: "Sliding Puzzle (15 Puzzle)",
    shortName: "Sliding Puzzle",
    relatedSlugs: ["game-2048", "sudoku"],
    ssr: false,
    group: "fun",
    priority: 0.63,
    changeFrequency: "monthly",
  },
  {
    slug: "block-stacker",
    category: "focus-study",
    icon: Blocks,
    name: "Block Stacker (Tetris-style Game)",
    shortName: "Block Stacker",
    relatedSlugs: ["snake-game", "game-2048"],
    ssr: false,
    group: "fun",
    priority: 0.68,
    changeFrequency: "monthly",
  },
  {
    slug: "sudoku",
    category: "focus-study",
    icon: Grid3x3,
    name: "Sudoku Puzzle",
    shortName: "Sudoku",
    relatedSlugs: ["minesweeper", "sliding-puzzle"],
    ssr: false,
    group: "fun",
    priority: 0.7,
    changeFrequency: "monthly",
  },

  {
    slug: "scientific-calculator",
    category: "math-calculators",
    icon: FlaskConical,
    name: "Scientific Calculator",
    shortName: "Scientific Calculator",
    relatedSlugs: ["graphing-calculator", "fraction-calculator"],
    ssr: false,
    priority: 0.9,
    changeFrequency: "monthly",
  },
  {
    slug: "graphing-calculator",
    category: "math-calculators",
    icon: ChartSpline,
    name: "Graphing Calculator",
    shortName: "Graphing Calculator",
    relatedSlugs: ["scientific-calculator", "quadratic-equation-solver"],
    ssr: false,
    priority: 0.85,
    changeFrequency: "monthly",
  },
  {
    slug: "fraction-calculator",
    category: "math-calculators",
    icon: Divide,
    name: "Fraction Calculator",
    shortName: "Fraction Calculator",
    relatedSlugs: ["scientific-calculator", "gcd-lcm-calculator"],
    ssr: false,
    priority: 0.84,
    changeFrequency: "monthly",
  },
  {
    slug: "matrix-calculator",
    category: "math-calculators",
    icon: Grid3x3,
    name: "Matrix Calculator",
    shortName: "Matrix Calculator",
    relatedSlugs: ["scientific-calculator", "statistics-calculator"],
    ssr: false,
    priority: 0.78,
    changeFrequency: "monthly",
  },
  {
    slug: "quadratic-equation-solver",
    category: "math-calculators",
    icon: Variable,
    name: "Quadratic Equation Solver",
    shortName: "Quadratic Solver",
    relatedSlugs: ["graphing-calculator", "scientific-calculator"],
    ssr: false,
    priority: 0.8,
    changeFrequency: "monthly",
  },
  {
    slug: "programmer-calculator",
    category: "math-calculators",
    icon: Binary,
    name: "Programmer Calculator (Hex, Binary, Bitwise)",
    shortName: "Programmer Calculator",
    relatedSlugs: ["scientific-calculator", "gcd-lcm-calculator"],
    ssr: false,
    priority: 0.76,
    changeFrequency: "monthly",
  },
  {
    slug: "statistics-calculator",
    category: "math-calculators",
    icon: Sigma,
    name: "Statistics Calculator",
    shortName: "Statistics Calculator",
    relatedSlugs: ["scientific-calculator", "matrix-calculator"],
    ssr: false,
    priority: 0.79,
    changeFrequency: "monthly",
  },
  {
    slug: "gcd-lcm-calculator",
    category: "math-calculators",
    icon: Hash,
    name: "GCD, LCM & Prime Factor Calculator",
    shortName: "GCD & LCM Calculator",
    relatedSlugs: ["fraction-calculator", "scientific-calculator"],
    ssr: false,
    priority: 0.74,
    changeFrequency: "monthly",
  },
  {
    slug: "schulte-table",
    category: "focus-study",
    icon: Grid3x3,
    name: "Schulte Table – Attention Training",
    shortName: "Schulte Table",
    relatedSlugs: ["stroop-test", "n-back-game"],
    ssr: false,
    group: "train",
    priority: 0.7,
    changeFrequency: "monthly",
  },
  {
    slug: "stroop-test",
    category: "focus-study",
    icon: Brain,
    name: "Stroop Test – Focus & Self-Control",
    shortName: "Stroop Test",
    relatedSlugs: ["schulte-table", "reaction-time-test"],
    ssr: false,
    group: "train",
    priority: 0.69,
    changeFrequency: "monthly",
  },
  {
    slug: "n-back-game",
    category: "focus-study",
    icon: Brain,
    name: "N-Back Working Memory Game",
    shortName: "N-Back Game",
    relatedSlugs: ["number-memory-game", "schulte-table"],
    ssr: false,
    group: "train",
    priority: 0.66,
    changeFrequency: "monthly",
  },
  {
    slug: "simon-game",
    category: "focus-study",
    icon: Music,
    name: "Simon Memory Pattern Game",
    shortName: "Simon Game",
    relatedSlugs: ["number-memory-game", "memory-match"],
    ssr: false,
    group: "train",
    priority: 0.65,
    changeFrequency: "monthly",
  },
  {
    slug: "number-memory-game",
    category: "focus-study",
    icon: Eye,
    name: "Number Memory Test",
    shortName: "Number Memory",
    relatedSlugs: ["simon-game", "n-back-game"],
    ssr: false,
    group: "train",
    priority: 0.64,
    changeFrequency: "monthly",
  },
  {
    slug: "aim-trainer",
    category: "focus-study",
    icon: Crosshair,
    name: "Aim Trainer & Click Accuracy Test",
    shortName: "Aim Trainer",
    relatedSlugs: ["reaction-time-test", "stroop-test"],
    ssr: false,
    group: "train",
    priority: 0.63,
    changeFrequency: "monthly",
  },
];

export function getToolBySlug(slug: string): ToolConfig | undefined {
  return TOOLS.find((tool) => tool.slug === slug);
}

/** Tools for a category, most-used-first (by editorial `priority`, descending). */
export function getToolsByCategory(category: ToolCategory): ToolConfig[] {
  return TOOLS.filter((tool) => tool.category === category).sort((a, b) => Number(!!b.featured) - Number(!!a.featured) || b.priority - a.priority);
}

export function getRelatedTools(tool: ToolConfig): ToolConfig[] {
  return tool.relatedSlugs
    .map((slug) => getToolBySlug(slug))
    .filter((t): t is ToolConfig => Boolean(t));
}
